%QUARTUS_ROOTDIR%\\bin\\quartus_pgm.exe -m jtag -c USB-Blaster[USB-0] -o "p;MTL_DEMO.sof"
@ set SOPC_BUILDER_PATH_71=%SOPC_KIT_NIOS2%+%SOPC_BUILDER_PATH_71%
@ set SOPC_BUILDER_PATH_72=%SOPC_KIT_NIOS2%+%SOPC_BUILDER_PATH_72%
@ set SOPC_BUILDER_PATH_80=%SOPC_KIT_NIOS2%+%SOPC_BUILDER_PATH_80%
@ set SOPC_BUILDER_PATH_81=%SOPC_KIT_NIOS2%+%SOPC_BUILDER_PATH_81%
@ set SOPC_BUILDER_PATH_90=%SOPC_KIT_NIOS2%+%SOPC_BUILDER_PATH_90%
@ set SOPC_BUILDER_PATH_91=%SOPC_KIT_NIOS2%+%SOPC_BUILDER_PATH_91%
@ set SOPC_BUILDER_PATH_92=%SOPC_KIT_NIOS2%+%SOPC_BUILDER_PATH_92%
@ set SOPC_BUILDER_PATH_100=%SOPC_KIT_NIOS2%+%SOPC_BUILDER_PATH_100%
@ set SOPC_BUILDER_PATH_101=%SOPC_KIT_NIOS2%+%SOPC_BUILDER_PATH_101%
@ set SOPC_BUILDER_PATH_102=%SOPC_KIT_NIOS2%+%SOPC_BUILDER_PATH_102%
@ set SOPC_BUILDER_PATH_110=%SOPC_KIT_NIOS2%+%SOPC_BUILDER_PATH_110%
@ set SOPC_BUILDER_PATH_111=%SOPC_KIT_NIOS2%+%SOPC_BUILDER_PATH_111%
@ set SOPC_BUILDER_PATH_112=%SOPC_KIT_NIOS2%+%SOPC_BUILDER_PATH_112%
@ set SOPC_BUILDER_PATH_120=%SOPC_KIT_NIOS2%+%SOPC_BUILDER_PATH_120%
@ set SOPC_BUILDER_PATH_121=%SOPC_KIT_NIOS2%+%SOPC_BUILDER_PATH_121%
@ set SOPC_BUILDER_PATH_122=%SOPC_KIT_NIOS2%+%SOPC_BUILDER_PATH_122%
@ set SOPC_BUILDER_PATH_130=%SOPC_KIT_NIOS2%+%SOPC_BUILDER_PATH_130%
@ set SOPC_BUILDER_PATH_131=%SOPC_KIT_NIOS2%+%SOPC_BUILDER_PATH_131%
@ set SOPC_BUILDER_PATH_132=%SOPC_KIT_NIOS2%+%SOPC_BUILDER_PATH_132%
@ set SOPC_BUILDER_PATH_140=%SOPC_KIT_NIOS2%+%SOPC_BUILDER_PATH_140%
@ set SOPC_BUILDER_PATH_141=%SOPC_KIT_NIOS2%+%SOPC_BUILDER_PATH_141%
@ set SOPC_BUILDER_PATH_142=%SOPC_KIT_NIOS2%+%SOPC_BUILDER_PATH_142%
@ set SOPC_BUILDER_PATH_150=%SOPC_KIT_NIOS2%+%SOPC_BUILDER_PATH_150%
@ set SOPC_BUILDER_PATH_151=%SOPC_KIT_NIOS2%+%SOPC_BUILDER_PATH_151%
@ set SOPC_BUILDER_PATH_152=%SOPC_KIT_NIOS2%+%SOPC_BUILDER_PATH_152%
@ "%QUARTUS_ROOTDIR%\bin\cygwin\bin\bash.exe" --rcfile ".\test_bashrc"
pause