#!/bin/sh
#
# This file was automatically generated by the Nios II IDE Flash Programmer.
#
# It will be overwritten when the flash programmer options change.
#

cd D:/richard/touch/CD_SOPC/DE2_SOPC_MTL_PAINTER/software/MTL_DEMO/Debug

# Creating .flash file for the FPGA configuration
"$SOPC_KIT_NIOS2/bin/sof2flash" --epcs --input="D:/richard/touch/CD_SOPC/DE2_SOPC_MTL_PAINTER/MTL_DEMO.sof" --output="MTL_DEMO.flash" 

# Programming flash with the FPGA configuration
"$SOPC_KIT_NIOS2/bin/nios2-flash-programmer" --epcs --base=0x00501800 --cable='USB-Blaster [USB-0]' --sidp=0x02000060 --id=0 --timestamp=1313734521 --instance=0 "MTL_DEMO.flash"

# Creating .flash file for the project
"$SOPC_KIT_NIOS2/bin/elf2flash" --base=0x00000000 --end=0x3fffff --reset=0x0 --input="MTL_DEMO.elf" --output="cfi_flash.flash" --boot="C:/altera/10.1/ip/altera/nios2_ip/altera_nios2/boot_loader_cfi.srec"

# Programming flash with the project
"$SOPC_KIT_NIOS2/bin/nios2-flash-programmer" --base=0x00000000 --cable='USB-Blaster [USB-0]' --sidp=0x02000060 --id=0 --timestamp=1313734521 --instance=0 "cfi_flash.flash"

